### ISSUE TITLE
Documentation for avi_systemconfiguration unclear and lacking examples

### ISSUE THREAD

**Issue by daunce** [avinetworks/ansible-collection-alb#73]
### Describe the bug

Doco for avi_systemconfiguration says dns_configuration is dict, but it's a list of dictionaries.

There's no example using the parameters within avi_systemconfiguration.

### Reproduction steps

```bash
None required
```

### Expected behavior

Provide example including:
```
  tasks:
    - name: Example to create SystemConfiguration object
      avi_systemconfiguration:
        avi_credentials: "{{ avi_credentials }}"
        state: present
        name: sample_systemconfiguration
        welcome_workflow_complete: True
        dns_configuration:
          search_domain: ''
          server_list:
          - type: V4
            addr: "8.8.8.8"
          - type: DNS
            addr: "dns.rainpole.com"
```
